### ISSUE TITLE
What's the minimum version of Node supported?

### ISSUE THREAD

**Issue by alebelcor** [wooorm/remark-lint#106]
It looks like this information is missing in `package.json` (and the `README`).

I imagine is something like [`remark`](https://github.com/wooorm/remark), i.e. `>=0.11.0` but I just wanted to confirm.

Thanks!

**Comment by wooorm** [comment]
It should run into 0.10, but I’m unsure about whether dependencies run there too. It definitely runs in 4.0.

The `>=0.11.0`, which should be `>=4.0.0` soon, is because I can only *test* remark / remark-lint in those engines (as some dev-dependencies require newer node versions).

That’s my guess, if you find where it breaks and where it works, I’d like to know about it too!
