### ISSUE TITLE
How create own preset(plugin) with own code style with new version

### ISSUE THREAD

**Issue by evilebottnawi** [wooorm/remark-lint#128]
I am very confusing, my last config https://github.com/itgalaxy/remark-preset-lint-itgalaxy now not work

**Comment by wooorm** [comment]
Correct, sorry about that. It sucks, but it was required, as the previous “presets” did not work on the API, and that was a big design mistake.

There’s two changes:

* plugins should be required in presets
* remark-lint changed too, every rule is a plugin, so instead of setting `blockquote-indentation` to `2`, you should now use something like `[require('remark-lint-blockquote-indentation'), 2]` instead.

I think [my personal preset](https://github.com/wooorm/remark-preset-wooorm/blob/master/index.js) will provide a good starting point.

Do let me know if you have any further questions, either below, or on Gitter!
