### ISSUE TITLE
YAML Frontmatter

### ISSUE THREAD

**Issue by mcnesium** [wooorm/remark-lint#154]
In [Atom](https://atom.io) it's marking errors in the YAML frontmatter of jekyll markdown files

![screenshot](https://user-images.githubusercontent.com/476060/28720696-35c02548-73ae-11e7-88b1-cec14f7f1ac7.png)

This is a false flag and should not be marked imho.

**Comment by mcnesium** [comment]
Also, it does not recognize comments in the frontmatter:

![screenshot2](https://user-images.githubusercontent.com/476060/28720757-679c9c18-73ae-11e7-8d62-3b7053bd664c.png)

**Comment by wooorm** [comment]
Hi @mcnesium!

remark itself supports YAML through [`remark-frontmatter`](https://github.com/wooorm/remark-frontmatter) (it used to be in the core, but was [externalised](https://github.com/wooorm/remark/releases/tag/8.0.0) recently). 

This issue is unrelated to `remark-lint`. I’m not sure how you use remark-lint is Atom. Maybe [`linter-markdown`](https://github.com/AtomLinter/linter-markdown)? If you can use plugins in Atom, you should add `remark-frontmatter` there. Otherwise, raise an issue on the thing using remark-lint in Atom.
