### ISSUE TITLE
Allow for Jekyll links

### ISSUE THREAD

**Issue by shaungrady** [wooorm/remark-lint#58]
I'm trying to use this linter with a [**Jekyll**](https://jekyllrb.com/) project, but Jekyll's programmatic links aren't supported. I would love to have Jekyll's use of the Liquid templating system supported.

![image](https://cloud.githubusercontent.com/assets/52413/14831940/9cd6f038-0bac-11e6-82c9-487a653feb21.png)

**Comment by wooorm** [comment]
What input are you talking about, for example, and what output do you expect?

**Comment by shaungrady** [comment]
Just expecting that `[link]({% variable %})` or `[link]({{ variable }})` be recognized as a link. Right now it parses it as a shortcut reference. Does that answer your question?

**Comment by wooorm** [comment]
OK, thanks, the image didn’t come through previously so it wasn’t exactly clear!

Thing is, what you’re writing isn’t markdown. Liquid’s syntax comes before markdown and, together with data, compiles to markdown (see mapbox/retext-mapbox-standard#6). And in turn, to HTML.

Put another way, there’s no way of knowing if some Liquid interpolation might return a URL (making it render as a link), or HTML, or even multiple paragraphs (making it something else).

And, finally, the fact that your syntax highlighter sees it as a link is because said highlighter is quite lax, whereas remark is more conforming.
