### ISSUE TITLE
`first-heading-level` rule should support `<h1>` too

### ISSUE THREAD

**Issue by sindresorhus** [wooorm/remark-lint#77]
I sometimes use `<h1>` instead because I need more control of the heading.

For example:

``` html
<h1 align="center">
    <br>
    <img width="400" src="https://cdn.rawgit.com/sindresorhus/awesome/master/media/logo.svg" alt="awesome">
    <br>
    <br>
    <br>
</h1>
```

**Comment by wooorm** [comment]
This is part of a bigger issue: I don’t want complete HTML parsing in remark, but it’s needed for this to be handled properly.

In the future, I’ll launch an HTML linter which could be used to check this, but it will not be part of remark-lint.

I would accept a PR to the first-heading rule which checks `html` nodes as well, and when they start with `\s+<h(\d)` use that as the first heading depth, but I’m personally not interested in working on that. So if anyone’s interested, feel free, I’ll gladly help! But I’m closing this here due to lack of interest :)

**Comment by sindresorhus** [comment]
Nobody will find it if it's closed though, why not keep it open until someone comes along and wants to fix it? I might get to this eventually.

**Comment by wooorm** [comment]
You’re right! I’d appreciate it if you/anyone wants to work on it!
