### ISSUE TITLE
Allow `<br>` in `no-html` rule

### ISSUE THREAD

**Issue by sindresorhus** [wooorm/remark-lint#80]
Or at least add an option to ignore it. In Markdown you can use two spaces at the end of a line to force a linebreak. I used to do that, but after having wasted countless of hours commenting on pull requests on people removing that whitespace either deliberately or accidentally, I've switched to explicitly use `<br>` instead. This is also much clearer.

**Comment by wooorm** [comment]
Closing for now, I’m still super open to it, but I don’t have time for it (apparently) on my own backlog. If anyone wants to work on this: ping me!

**Comment by sindresorhus** [comment]
Same reply as https://github.com/wooorm/remark-lint/issues/77#issuecomment-236725397

**Comment by vanyauhalin** [comment]
Hey, Titus, question. If I were to add a `tags` option, similar to the existing `flags` option in the `remark-lint-fenced-code-flag`, would you be open to accepting it? I am asking because I am not entirely clear on the `no/wontfix` badge.

**Comment by wooorm** [comment]
Hey! Label is more due to it being old.
It wouldn‘t work as well. For markdown, `</div><br>` is valid html. Meaning, we have strings of broken stuff that we can’t properly look into. It also doesn’t have to be HTML, but could be anything that looks like XML.
Fenced code flag is a single word, easier to look up.
